### ISSUE TITLE
Netzbetreiber unbekannt trotz Netz NÖ

### ISSUE THREAD

**Issue by sysadmvienna** [awattar-backtesting/awattar-backtesting.github.io#32]
When uploading a yearly csv file from NetzNÖ I am getting the error message "Netzbetreiber unbekannt. check console".
I can provide my csv file but do not want to share with the entire internet.
Please message me so I can send it to you for debugging purposes.

**Comment by lefduti** [comment]
Yeah NetzNÖ changed their csv file. Instead of "Ersatzwert" there is now "Qualität". It has to be changed in the code.

**Comment by sysadmvienna** [comment]
Ah I think I found another bug in NetzNÖ CSV file:

I am part of an "Erneuerbare Energien Gemeinschaft" where I can get cheap power from my region when it's available. So my CSV header looks like this:


Messzeitpunkt;Verbrauch (kWh);Restnetzbezug (kWh);Eigendeckung (kWh);Ideeller Anteil (kWh);Eigendeckung erneuerb. Energie (kWh);

**Comment by lewurm** [comment]
Thanks for the report!  I pushed a quickfix so that exports without EEG participation still works.

Although I'm customer at NetzNÖ myself, I'm not part of an EEG. Could someone provide an export?

Also it raises the question how the tool should account for it: Should it
1. use the `Verbrauch (kWh)` column and thus ignore any third party energy income, or
2. use `Restnetzbezug (kWh)` so it actually maps to the invoice by the energy provider at the end of the month.


I would prefer the latter option for now.

**Comment by sysadmvienna** [comment]
Here you go:
[eeg-example.csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/13936462/eeg-example.csv)

I'd also prefer the latter option because that would be the amount which has to be bought from the primary energy vendor.

**Comment by lewurm** [comment]
Thanks again @sysadmvienna, should work now 🙂
